---
title: "Bringing XLSXy back"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## What's the plan?

In this activity, we're going to create a new RStudio project, add a basic skeleton of folders to it, then download some real world data and try to clean it up. 
Our example data are point in time homelessness counts from all communities of care in the US between 2007 and 2018.

## Creating the project

1. Click file > new project
2. Create the project in a new directory
3. Name the project something appropriate
4. Set up your folders
  + R: where your R scripts live (all of them)
  + data: where all of the data lives (ALL OF IT)
    - raw: fresh files, completely untouched
    - clean: your clean analysis data sets
  + output: where all the direct pieces of output you make live
5. Celebrate!

## Do some stuff!!

### Download the data

Click [here](https://drive.google.com/open?id=1KRodWm2y7Ays5hcVmHagQLcv4ljBNHb1) to navigate to the file on google drive.  
Once there, download the file as an excel workbook. 

### Make a script

Make a new script in your R folder. Call it something like "clean-data.R". 
The script should do the following: 

- Read all the sheets in the excel workbook into one data frame
- Tidy the data frame 
- Select relevant variables for the analysis
- Save your tidy data set in the clean folder with a sensible name
- Make a summary table that is interesting in some way. 
